# Generated by Django 4.1.7 on 2023-04-04 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discos',
            options={'ordering': ['nome'], 'verbose_name': 'Disco', 'verbose_name_plural': 'Discos'},
        ),
    ]
