# Generated by Django 4.1.7 on 2023-03-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('idade', models.CharField(max_length=11, verbose_name='Telefone')),
                ('telefone', models.IntegerField(blank=True, null=True, verbose_name='Telefone')),
            ],
        ),
    ]
