from crud_firebase import CrudFirebase
crud = CrudFirebase()

# lista = ['ANDRE RICARDO PRAZERES RODRIGUES','LIVIA FERREIRA VIDAL','YALACE DE SOUZA MARQUES','GUILHERME DE DEUS PATROCINIO CAVALHEIRO CUNHA','BRIAN FERREIRA FEITOSA DE OLIVEIRA','DETLEY MARTINS DE ANDRADE','BRUNO DE CARVALHO PEREIRA','IRVING LUI DE SOUZA CAETANO','LUAN DE PAIVA FARANI','MATHEUS DE SOUZA VIGA OLIVEIRA','LUCIANE DO LIVRAMENTO ANDRADE CORDEIRO','DIEGO DE OLIVEIRA CORTEZ DE LIMA','MATHEUS EDUARDO DE OLIVEIRA MARIINS ALVES','RAQUEL LEAL LOPES','GUSTAVO REIS CARRARO DE CASTRO','JOAO PEDRO PACIELLO SOBRINHO RIBEIRO','GUSTAVO DE MENEZES COSTA TOBIAS','EDUARDO ALVES TOLEDO','DANIEL CERQUEIRA HALFELD','ARTHUR SANTANA RIBEIRO','VITOR NUNES DE OLIVEIRA BESSA','ORLANDO SILVA SIQUEIRA FILHO','THOMAS LUCAS BOCKORNI DA SILVA','MATHEUS PONTES MACEDO','GABRIEL MIRANDA DE OLIVEIRA NOVAES','PEDRO HENRICO AFONSO PINTO','FELIPE SILVA DE FREITAS','ARTHUR RANGEL DE CARVALHO SOUZA','LARISSA FERNANDES CARIUS','KAICK DE SOUZA FREITAS','ANDERSON VIEIRA DA SILVA OLIVEIRA','JOUBERT FELIPE PINHEIRO','DRIELLI BORGES COSTA','FILLIPE GOMES PEREIRA','GABRIEL PEREIRA DA COSTA','BARBARA CARVALHO MIRANDA','GUSTAVO DE SOUZA CERQUEIRA','PAULO THIAGO DAMIAO DE OLIVEIRA','DANIEL DA SILVA RIBEIRO','GABRYEL DA SILVA GORITO','ABNER BATISTA SILVA','MARIA GABRIELA COSTA DA SILVA OLIVEIRA','VINICIOS CONDE ATAIDE','CICERO MORAES MATTOS DE PAULA','MATHEUS DA CUNHA ALVES','MANUELA OLIVEIRA MARINHO CAMPOS','PAULO HENRIQUE DA SILVA RAPOSO','IVAN AUGUSTO COSTA GOMES','JOAO PEDRO PAIVA SOARES','LUCAS COUTINHO SOARES MORAES','GUILHERME DE MELO WERNECK','LEONARDO GOMES DE OLIVEIRA FERREIRA','KAUE SOUZA PINTO','RANGEL PEREIRA DE ALCANTARA','THIAGO GOMES COUTINHO','PEDRO PAULO SCHWENCK BARBOSA','FLAVIO NOVAES DE OLIVEIRA','P BRUCE HENRIQUE DE MORAES MOREIRA','CARLOS EDUARDO FERREIRA','VITOR HUGO CAMPOS DE SOUZA','CARLOS ALBERTO MARTINS SOARES JUNIOR','GUILHERME RAMOS RIBEIRO','THIAGO GAMA MARCAL','KAIO GONCALVES PEREIRA','JULLYANA MARTINS JOSEFINO DA SILVA','DIEGO FIALHO ELLES','BEATRIZ CARVALHO DO NASCIMENTO']
# for i in range(len(lista)):
#     nome = lista[i],
#     matricula = ''
#     dados = {
#         'nome' : nome,
#         'matricula' : matricula
#     }
chave = ''
resultados = (crud.ler_alunos(chave))
for resultado in resultados:
    print(resultado.key())
    print(resultado.val())